routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('orcamentos', 'OrcamentoController');
Route::resource('formulas', 'FormulaController');
Route::resource('componentes', 'ComponenteController');
Route::resource('precos', 'PrecoController');

app/Orcamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Orcamento extends Model
{
    protected $fillable = ['status','cliente_id','vendedor_id'];

    public function vendedor()
    {
        $this->hasOne(User::class);
    }

    public function cliente()
    {
        $this->hasOne(User::class);
    }
}

app/Http/Controllers/OrcamentoController.php
<?php

namespace App\Http\Controllers;

use App\Orcamento;
use App\User;
use Illuminate\Http\Request;

class OrcamentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orcamentos = Orcamento::paginate();
        return view('orcamento.index', compact('orcamentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::paginate(7);
        return view('orcamento.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dados = $request->all();
        $dados['status'] = 'incompleto';
        $dados['vendedor_id'] = User::inRandomOrder()->first()->id;
        $orcamento = Orcamento::create($dados);
        $orcamentoId = $orcamento->id;
        //pega o cliente e salva
        //pega um vendedor aleatorio
        //salva o orcamento e devolve o id
        //$orcamentoId = 1;
        return redirect()->route('formulas.create', compact('orcamentoId'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('orcamento.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('orcamento.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orcamento/_form.blade.php
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Nome</th>
        <th>CPF</th>
        <th>E-mail</th>
    </tr>
    </thead>
    <tbody>
    @foreach($users as $user)
        <tr>
            <td>
                <div class="radio">
                    <label>
                        <input type="radio" name="cliente_id" value="{{$user->id}}">
                    </label>
                </div>
            </td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->cpf }}</td>
            <td>{{ $user->email }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
{{ $users->links() }}

resources/views/orcamento/create.blade.php
@extends('layouts.app')

@section('header')
    <header id="header">
        <h1>Novo Orçamento</h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Home</a></li>
            <li class="active">Orçamentos</li>
        </ol>
    </header>
@endsection

@section('body')
    <div class="row">

        <div class="col-xs-12">
            <div class="card">
                <form method="post" action="{{ route('orcamentos.store') }}">
                    {{ csrf_field() }}
                <header class="card-heading ">
                    <h2 class="card-title">Adicionar o Cliente</h2>
                    <small>Escolha o Cliente</small>

                    <ul class="card-actions icons right-top">
                        <li>
                            <button class="btn btn-primary" type="submit">Adicionar Formulas</button>
                        </li>
                    </ul>
                </header>
                <div class="card-body">
                        @include('orcamento._form')
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/orcamento/edit.blade.php
edit

resources/views/orcamento/index.blade.php
@extends('layouts.app')

@section('header')
    <header id="header">
        <h1>Orçamentos</h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('home') }}">Home</a></li>
            <li class="active">Orçamentos</li>
        </ol>
    </header>
@endsection

@section('body')
    <div class="row">

        <div class="col-xs-12">
            <div class="card">
                <header class="card-heading ">
                    <h2 class="card-title">Card Header</h2>
                    <small>Paleo flexitarian bushwick letterpress</small>
                </header>
                <div class="card-body">
                    <a class="btn btn-primary" href="{{route('orcamentos.create')}}">Novo Orcamento</a>
                    lista Orçamentos
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/orcamento/show.blade.php
show