routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('orcamentos', 'OrcamentoController');
Route::resource('formulas', 'FormulaController');
Route::resource('componentes', 'ComponenteController');
Route::resource('precos', 'PrecoController');

resources/views/layouts/_footer.blade.php
<footer id="footer_wrapper" >
    <div class="footer-content">

        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <h6>Want to Work with Us?</h6>
                <p>Paleo flexitarian bushwick letterpress, ea migas yr adipisicing. Man bun tacos tumblr kombucha, yuccie banjo affogato dolore gentrify retro chartreuse. Anim austin tempor ethical, sapiente food truck fanny pack farm-to-table. Culpa keytar esse
                    tilde hoodie, art party nostrud messenger bag authentic helvetica kinfolk cred eu affogato forage.</p>
            </div>
            <div class="col-xs-12 col-sm-2">
                <h6>Company</h6>
                <ul>
                    <li><a href="javascript:void(0)">About Us </a></li>
                    <li><a href="javascript:void(0)">Careers</a></li>
                    <li><a href="javascript:void(0)">Privacy Policy</a></li>
                    <li><a href="javascript:void(0)">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4">
                <h6>Email Newsletters</h6>
                <p>Sign up for new MaterialWrap content, updates, and offers.</p>
                <div class="form-group is-empty">
                    <div class="input-group">
                        <label class="control-label sr-only" for="footerEmail">Email Address</label>
                        <input type="email" class="form-control" id="footerEmail" placeholder="Enter your email address...">
                        <span class="input-group-btn">
								<button type="button" class="btn btn-white btn-fab animate-fab btn-fab-sm">
									<i class="zmdi zmdi-mail-send"></i>
								</button>
							</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row copy-wrapper">
            <div class="col-xs-8">
                <p class="copy">&copy; Copyright <time class="year"></time> MaterialWrap - All Rights Reserved</p>
            </div>
            <div class="col-xs-4">
                <ul class="social">
                    <li>
                        <a href="javascript:void(0)"> </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"> </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"> </a>
                    </li>
                    <li>
                        <a href="javascript:void(0)"> </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/_header.blade.php
<header id="app_topnavbar-wrapper">
    <div class="container-fluid">
        <nav role="navigation" class="navbar topnavbar">
            <div class="nav-wrapper">

                <div class="navbar-header">
                    <a href="{{ route('home') }}">
                        <h1 class="brand-text md-text-black-50">{{ config('app.name', 'AppFarma') }}</h1>
                    </a>
                </div>

                @if (Auth::user())
                    <ul class="nav navbar-nav left-menu">
                        <li><a href="{{ route('orcamentos.index') }}">Orçamentos</a></li>
                        <li><a href="app-mail.html">Pedidos</a></li>
                        <li><a href="app-mail.html">Relatorios</a></li>
                    </ul>

                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown avatar-menu">
                            <a href="javascript:void(0)" data-toggle="dropdown" aria-expanded="false">
								<span class="meta">
									<span class="avatar">
										<i class="zmdi zmdi-account"></i>
										<i class="badge mini success status"></i>
									</span>
									<span class="name"> {{ Auth::user()->name }}</span>
									<span class="caret"></span>
								</span>
                            </a>
                            <ul class="dropdown-menu btn-primary dropdown-menu-right">
                                <li>
                                    <a href="page-profile.html"><i class="zmdi zmdi-account"></i> Profile</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><i class="zmdi zmdi-settings"></i> Account Settings</a>
                                </li>
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="zmdi zmdi-sign-in"></i> Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                @else
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    </ul>
                @endif

            </div>
        </nav>
    </div>
</header>

resources/views/layouts/_menu.blade.php
<aside id="app_sidebar-left">
    <div id="logo_wrapper">
        <ul>
            <li class="logo-icon">
                <a href="{{ route('home') }}">
                    <div class="logo">
                        {{--<img src="assets/img/logo/logo-icon.png" alt="Logo">--}}
                    </div>
                    <h1 class="brand-text">{{ config('app.name', 'Azevedo Bastos') }}</h1>
                </a>
            </li>
            <li class="menu-icon">
                <a href="javascript:void(0)" role="button" data-toggle-state="app_sidebar-menu-collapsed" data-key="leftSideBar">
                    <i class="mdi mdi-backburger"></i>
                </a>
            </li>
        </ul>
    </div>
    <nav id="app_main-menu-wrapper" class="scrollbar">
        <div class="sidebar-inner sidebar-push">
            <ul class="nav nav-pills nav-stacked">
                <li class="sidebar-header">NAVIGATION</li>
                <li class="{{ route_state('home') }}"><a href="{{ route('home') }}"><i class="zmdi zmdi-view-dashboard"></i>Inicio</a></li>
                <li class="nav-dropdown {{ route_state(['nascimento.*','casamento.*']) }}">
                    <a href="#"><i class="zmdi zmdi-view-quilt"></i>Certidão</a>
                    <ul class="nav-sub">
                        <li class="nav-dropdown">
                            <a href="#">Nascimento </a>
                            <ul class="nav-sub">
                                <li><a href="#">Novo registro</a></li>
                                <li><a href="#">Registro em Andamento</a></li>
                                <li><a href="{{ route('nascimento.index') }}">Busca Registro</a></li>
                                <li><a href="#">Importar Registro</a></li>
                            </ul>
                        </li>
                        <li class="nav-dropdown">
                            <a href="#">Casamento</a>
                            <ul class="nav-sub">
                                <li><a href="#">Novo Registro</a></li>
                                <li><a href="#">Registro em Andamento</a></li>
                                <li><a href="#">Aguardando Retirada</a></li>
                                <li><a href="#">Busca Registro</a></li>
                            </ul>
                        </li>
                        <li class="nav-dropdown">
                            <a href="#">Obito</a>
                            <ul class="nav-sub">
                                <li><a href="#">Novo Registro</a></li>
                                <li><a href="#">Busca Registro</a></li>

                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nav-dropdown {{ route_state('solicitacao.*') }}"><a href="#"><i class="zmdi zmdi-widgets"></i>Segunda Via</a>
                    <ul class="nav-sub">
                        <li><a href="#">Solicitar</a></li>
                        <li><a href="{{ route('solicitacao.index') }}">Solicitações Pendentes</a></li>
                        <li><a href="#">Aguardando retirada</a></li>
                        <li><a href="#">Solicitações Concluidas</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown  {{ route_state('anotacao.*') }}"><a href="#"><i class="zmdi zmdi-chart"></i>Anotações </a>
                    <ul class="nav-sub">
                        <li><a href="#">Nova Anotação</a></li>
                        <li><a href="{{ route('anotacao.index') }}">Indice</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown {{ route_state('reconhecimento-firma.*') }}"><a href="#"><i class="zmdi zmdi-chart"></i>Reconhecimento de Firma</a>
                    <ul class="nav-sub">
                        <li><a href="{{ route('reconhecimento-firma.index') }}">Reconhecer Firma</a></li>
                        <li><a href="#">Reconhecimento Mensalista</a></li>
                        <li><a href="#">Novo Cliente</a></li>
                        <li><a href="#">Buscar</a></li>
                        <li><a href="#">Relatório</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown  {{ route_state('autenticacao.*') }}"><a href="#"><i class="zmdi zmdi-chart"></i>Autenticação</a>
                    <ul class="nav-sub">
                        <li><a href="#">Nova Autenticação</a></li>
                        <li><a href="#">Nova Autenticação + copia</a></li>
                        <li><a href="#">Cópias</a></li>
                        <li><a href="#">Relatorios</a></li>
                        <li><a href="#">Solicitações Autenticação Digital</a></li>
                        <li><a href="#">Nova Autenticação Digital</a></li>
                        <li><a href="#">Relatorio</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown {{ route_state('mensalista.*') }}"><a href="#"><i class="zmdi zmdi-chart"></i>Cliente PJ</a>
                    <ul class="nav-sub">
                        <li><a href="{{ route('mensalista.index') }}">Clientes</a></li>
                        <li><a href="{{ route('mensalista.create') }}">Novo Cliente</a></li>
                        <li><a href="#">Relatorio Mensalista</a></li>
                    </ul>
                </li>
                <li class="nav-dropdown {{ route_state('autenticacao.*') }}"><a href="#"><i class="zmdi zmdi-chart"></i>Caixa</a>
                    <ul class="nav-sub">
                        <li><a href="#">Autenticação Digital</a></li>
                        <li><a href="#">Autenticação Digital Mensalista</a></li>
                        <li><a href="#">Autenticação Digital Fortaleza</a></li>
                        <li><a href="#">Caixa</a></li>
                    </ul>
                </li>
                <li class="sidebar-header">Ferramenta</li>

                <li class="{{ route_state('texto.*') }}"><a href="#"><i class="zmdi zmdi-folder"></i>Novo Texto</a></li>
                <li class="{{ route_state('atos.*') }}"><a href="#"><i class="zmdi zmdi-view-column"></i>Tipos de Atos</a></li>
                <li class="{{ route_state('atos.*') }}"><a href="#"><i class="mdi mdi-lightbulb"></i>Atos Simples</a></li>
                <li class="{{ route_state('atos.*') }}"><a href="#"><i class="zmdi zmdi-email"></i>Atos Compostos</a></li>

                <li class="sidebar-header">Usuario</li>
                <li><a href="#"><i class="zmdi zmdi-account"></i>Alterar dados</a></li>

                <li class="sidebar-header">Permissões</li>
                <li class="{{ route_state('cargos') }}"><a href="{{ route('cargos') }}"><i class="zmdi zmdi-folder"></i>Cargos</a></li>
                <li class="{{ route_state('permissao') }}"><a href="{{ route('permissao') }}"><i class="zmdi zmdi-folder"></i>Permissões</a></li>
            </ul>
        </div>
    </nav>
</aside>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('theme/css/vendor.bundle.css') }}" rel="stylesheet">
    <link href="{{ asset('theme/css/app.bundle.css') }}" rel="stylesheet">
    <link href="{{ asset('theme/css/theme-a.css') }}" rel="stylesheet">
</head>
<body>
<div id="app_wrapper">

    @include('layouts._header')

    <section id="content_outer_wrapper" style="padding-left: 0 !important;">
        <div id="content_wrapper" class="card-overlay">
            <div id="header_wrapper" class="header-md">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            @yield('header')
                        </div>
                    </div>
                </div>
            </div>

            <div id="content" class="container">

                @yield('body')

            </div>
        </div>

        @include('layouts._footer')
    </section>




</div>


{{--<script src="{{ asset('js/app.js') }}"></script>--}}
<script src="{{ asset('theme/js/vendor.bundle.js') }}"></script>
<script src="{{ asset('theme/js/app.bundle.js') }}"></script>
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('theme/css/vendor.bundle.css') }}" rel="stylesheet">
    <link href="{{ asset('theme/css/app.bundle.css') }}" rel="stylesheet">
    <link href="{{ asset('theme/css/theme-a.css') }}" rel="stylesheet">
</head>
<body>
<div id="app_wrapper">

    <header id="app_topnavbar-wrapper">
        <div class="container-fluid">
            <nav role="navigation" class="navbar topnavbar">
                <div class="nav-wrapper">

                    <div class="navbar-header">
                        <a href="{{ route('home') }}">
                            <h1 class="brand-text md-text-black-50">{{ config('app.name', 'AppFarma') }}</h1>
                        </a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>


    <section id="content_outer_wrapper" style="padding-left: 0 !important;">
        <div id="content_wrapper" class="card-overlay">
            <div id="header_wrapper" class="header-md">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-12">
                            @yield('header')
                        </div>
                    </div>
                </div>
            </div>

            <div id="content" class="container-fluid">

                @yield('body')

            </div>
        </div>

    </section>
</div>


{{--<script src="{{ asset('js/app.js') }}"></script>--}}
<script src="{{ asset('theme/js/vendor.bundle.js') }}"></script>
<script src="{{ asset('theme/js/app.bundle.js') }}"></script>
</body>
</html>